version: '3.4'

services:
  onboarding.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ScreeningApi__Endpoint=http://screening-api
      - ScreeningApi__Authority=https://screening-idp
      - AZURE_TENANT_ID
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  externalscreening.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IdentityServer__Authority=http://screening-idp
      - IdentityServer__Issuers=https://screening-idp;https://localhost:8445
      - OnboardingApi__Endpoint=http://onboarding-app
      - OnboardingApi__Authority=https://ca-identity-server.politewater-ba7a3a0c.westeurope.azurecontainerapps.io #needs to be reachable by AAD over the public internet
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  externalscreening.idp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Onboarding
      - ASPNETCORE_Kestrel__Certificates__Default__Path=certificate.pfx
    ports:
      - "8082:80"
      - "8445:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro